### ISSUE TITLE
Cannot import name prompt

### ISSUE THREAD

**Issue by Manaus** [AnsonT/pocket2quiver#1]
```
Traceback (most recent call last):
  File "pocket2quiver.py", line 27, in <module>
    from prompt_toolkit import prompt
ImportError: cannot import name prompt
```

Using python 2.7.10 here
Thanks

**Comment by AnsonT** [comment]
This was built with Python 3.5.2. I haven't tried building in 2.7.x because of unicode inconsistency with some of the libraries used.

I also haven't created the setup script yet. Please make sure you run 
pip install -r requirements.txt
